# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: joplin_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: joplin_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

  tags:
    - setup-all
    - setup-joplin-server
    - install-all
    - install-joplin-server

- block:
    - when: not joplin_server_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-joplin-server
