# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Send installation tasks
  when: send_enabled | bool
  tags:
    - setup-all
    - setup-send
    - install-all
    - install-send
  block:
    - name: Validate Send configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Send
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Send uninstallation tasks
  when: not send_enabled | bool
  tags:
    - setup-all
    - setup-send
  block:
    - name: Uninstall Send
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
