# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Send systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ send_identifier }}.service"
  register: send_service_stat

- name: Uninstall Send systemd services and files
  when: send_service_stat.stat.exists | bool
  block:
    - name: Ensure Send systemd service is stopped
      ansible.builtin.service:
        name: "{{ send_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Send systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ send_identifier }}.service"
        state: absent

    - name: Ensure Send support files do not exist
      ansible.builtin.file:
        path: "{{ send_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Send image source files path does not exist
      ansible.builtin.file:
        path: "{{ send_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Send container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ send_container_network }}"
        state: absent

    - name: Ensure Send container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ send_container_network }}
      register: network_deletion_result
      changed_when: send_container_network in network_deletion_result.stdout

- name: Check existence of Send local data path
  ansible.builtin.stat:
    path: "{{ send_data_path }}"
  register: send_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Send local data remains
  when: send_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Send instance has been removed, some old data remains in `" + send_data_path + "`. Feel free to delete it."
        ]
      }}
