# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { 'old': 'send_environment_variable_S3_bucket', 'new': 'send_environment_variable_s3_bucket' }
    - { 'old': 'send_environment_variable_S3_endpoint', 'new': 'send_environment_variable_s3_endpoint' }
    - { 'old': 'send_environment_variable_S3_use_path_style_endpoint', 'new': 'send_environment_variable_s3_use_path_style_endpoint' }

- name: Fail if required Send settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - send_uid
    - send_gid
    - send_hostname
    - send_path_prefix
    - send_container_network
    - send_environment_variable_redis_host

- name: Run if Traefik is enabled
  when: send_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Send Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - send_container_labels_traefik_hostname
        - send_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `send_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if send_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          send_container_labels_traefik_path_prefix (`{{ send_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/send`).
      when: "send_container_labels_traefik_path_prefix != '/' and send_container_labels_traefik_path_prefix[-1] == '/'"
